export const en = {
  "actionSheet.cancelHint": "Closes the confirmation sheet",
  "actionSheet.confirmHint": "Confirms the selected action",
  "app.tab.home": "Home",
  "app.tab.sessions": "Sessions",
  "common.cancel": "Cancel",
  "common.close": "Close",
  "common.confirm": "Confirm",
  "common.date": "Date",
  "common.delete": "Delete",
  "common.duration": "Duration",
  "common.finish": "Finish",
  "common.keep": "Keep",
  "counter.addButton": "Add",
  "counter.countLabel": "Quantity {{count}}",
  "counter.createHint": "Creates a new counter with the given name",
  "counter.createLabel": "Create counter",
  "counter.decrementHint": "Decreases the counter by one",
  "counter.decrementLabel": "Subtract from {{name}}",
  "counter.deleteHint": "Deletes this counter",
  "counter.deleteLabel": "Delete {{name}}",
  "counter.deleteMessage": 'Delete "{{name}}"? This action cannot be undone.',
  "counter.deleteTitle": "Delete counter",
  "counter.helperMax": "Maximum {{max}} characters",
  "counter.incrementHint": "Increases the counter by one",
  "counter.incrementLabel": "Add to {{name}}",
  "counter.nameHint": "Type the counter name and press create",
  "counter.nameLabel": "Counter name",
  "counter.placeholder": "Dish",
  "counter.placeholderDefault": "Type a name for the counter",
  "export.button": "Export session",
  "export.error": "Error exporting the session",
  "export.generating": "Generating...",
  "export.hint": "Generates an image with the session summary",
  "export.imageMissing": "Couldn't generate the image",
  "image.authError": "Couldn't authenticate with the server",
  "image.generateError": "Couldn't generate the image",
  "image.label": "Image of {{name}}",
  "image.missingApiUrl": "EXPO_PUBLIC_IMAGE_API_URL is not configured",
  "image.noImage": "No image",
  "image.serviceInvalid": "Invalid response from image service",
  "image.generating": "Generating...",
  "session.defaultName": "Restaurant",
  "session.deleteHint": "Asks for confirmation to delete the session",
  "session.deleteLabel": "Delete session {{name}}",
  "session.deleteMessage":
    'The session "{{name}}" will be deleted. This action cannot be undone.',
  "session.deleteTitle": "Delete session",
  "session.emptyCounters": "There are no counters in this session",
  "session.endButton": "End session",
  "session.endButtonHint": "Shows a confirmation to end the session",
  "session.endButtonLabel": "End session",
  "session.endMessage":
    "You won't be able to add more counters until you start a new session.",
  "session.endTitle": "End session",
  "session.metaLine": "Date: {{date}}, Start time: {{time}}, Duration: {{duration}}",
  "session.notFoundSubtitle": "Go back to the list and select another session.",
  "session.notFoundTitle": "Session not found",
  "session.restaurantHint": "It will be used as the session name",
  "session.restaurantLabel": "Restaurant name",
  "session.restaurantPlaceholder": "Restaurant",
  "session.startButton": "Start",
  "session.startButtonHint": "Starts a session with the restaurant name",
  "session.startButtonLabel": "Start session",
  "session.startTitle": "Start the session",
  "sessions.back": "Back to sessions",
  "sessions.cardA11yHint": "Opens the session detail",
  "sessions.cardA11yLabel":
    "{{name}}. Date {{date}}. Duration {{duration}}. Different dishes {{count}}. Pieces {{total}}.",
  "sessions.distinctPlates": "Different dishes",
  "sessions.emptySubtitle": "Start and end a session to see it here.",
  "sessions.emptyTitle": "No sessions yet",
  "sessions.pieces": "Pieces",
  "time.hour": "{{count}} hour",
  "time.hours": "{{count}} hours",
  "time.minute": "{{count}} minute",
  "time.minutes": "{{count}} minutes",
  "time.second": "{{count}} second",
  "time.seconds": "{{count}} seconds",
} as const;
