export const es = {
  "actionSheet.cancelHint": "Cierra el cuadro de confirmación",
  "actionSheet.confirmHint": "Confirma la acción seleccionada",
  "app.tab.home": "Inicio",
  "app.tab.sessions": "Sesiones",
  "common.cancel": "Cancelar",
  "common.close": "Cerrar",
  "common.confirm": "Confirmar",
  "common.date": "Fecha",
  "common.delete": "Eliminar",
  "common.duration": "Duración",
  "common.finish": "Finalizar",
  "common.keep": "Mantener",
  "counter.addButton": "Añadir",
  "counter.countLabel": "Cantidad {{count}}",
  "counter.createHint": "Crea un nuevo contador con el nombre indicado",
  "counter.createLabel": "Crear contador",
  "counter.decrementHint": "Disminuye el contador en uno",
  "counter.decrementLabel": "Restar a {{name}}",
  "counter.deleteHint": "Borra este contador",
  "counter.deleteLabel": "Eliminar {{name}}",
  "counter.deleteMessage": '¿Eliminar "{{name}}"? Esta acción no se puede deshacer.',
  "counter.deleteTitle": "Eliminar contador",
  "counter.helperMax": "Máximo {{max}} caracteres",
  "counter.incrementHint": "Aumenta el contador en uno",
  "counter.incrementLabel": "Sumar a {{name}}",
  "counter.nameHint": "Escribe el nombre del contador y pulsa añadir",
  "counter.nameLabel": "Nombre del contador",
  "counter.placeholder": "Plato",
  "counter.placeholderDefault": "Escribe un nombre para el contador",
  "export.button": "Exportar sesión",
  "export.error": "Error al exportar la sesión",
  "export.generating": "Generando...",
  "export.hint": "Genera una imagen con el resumen de la sesión",
  "export.imageMissing": "No se pudo generar la imagen",
  "image.authError": "No se pudo autenticar con el servidor",
  "image.generateError": "No se pudo generar la imagen",
  "image.label": "Imagen de {{name}}",
  "image.missingApiUrl": "Falta configurar EXPO_PUBLIC_IMAGE_API_URL",
  "image.noImage": "Sin imagen",
  "image.serviceInvalid": "Respuesta inválida del servicio de imágenes",
  "image.generating": "Generando...",
  "session.defaultName": "Restaurante",
  "session.deleteHint": "Pide confirmación para eliminar la sesión",
  "session.deleteLabel": "Eliminar sesión {{name}}",
  "session.deleteMessage":
    'Se eliminará la sesión "{{name}}". Esta acción no se puede deshacer.',
  "session.deleteTitle": "Eliminar sesión",
  "session.emptyCounters": "No hay contadores en esta sesión",
  "session.endButton": "Finalizar sesión",
  "session.endButtonHint": "Muestra una confirmación para finalizar la sesión",
  "session.endButtonLabel": "Finalizar sesión",
  "session.endMessage": "No podrás añadir más contadores hasta iniciar una nueva sesión.",
  "session.endTitle": "Finalizar sesión",
  "session.metaLine": "Fecha: {{date}}, Hora inicio: {{time}}, Duración: {{duration}}",
  "session.notFoundSubtitle": "Vuelve a la lista y selecciona otra sesión.",
  "session.notFoundTitle": "Sesión no encontrada",
  "session.restaurantHint": "Se usará como nombre de la sesión",
  "session.restaurantLabel": "Nombre del restaurante",
  "session.restaurantPlaceholder": "Restaurante",
  "session.startButton": "Empezar",
  "session.startButtonHint": "Inicia una sesión con el nombre del restaurante",
  "session.startButtonLabel": "Empezar sesión",
  "session.startTitle": "Inicia la sesión",
  "sessions.back": "Volver a sesiones",
  "sessions.cardA11yHint": "Abre el detalle de la sesión",
  "sessions.cardA11yLabel":
    "{{name}}. Fecha {{date}}. Duración {{duration}}. Platos diferentes {{count}}. Piezas {{total}}.",
  "sessions.distinctPlates": "Platos diferentes",
  "sessions.emptySubtitle": "Inicia y finaliza una sesión para verla aquí.",
  "sessions.emptyTitle": "No hay sesiones aún",
  "sessions.pieces": "Piezas",
  "time.hour": "{{count}} hora",
  "time.hours": "{{count}} horas",
  "time.minute": "{{count}} minuto",
  "time.minutes": "{{count}} minutos",
  "time.second": "{{count}} segundo",
  "time.seconds": "{{count}} segundos",
} as const;
